name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        # working-directory: /home/runner/work/evtx2pandas
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ls
      - run: pwd
      - run: pip install -r requirements.txt
      - run: pip install pylint yapf pytest
      - run: pylint
      - run: yapf
      - run: pytest